name: Mkdocs

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        python-version:
          - 3.12

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: python/pdm.lock

      - name: Install dependencies
        run: ./python/scripts/install-deps.sh

      # - name: Debug
      #   uses: mxschmitt/action-tmate@v3

      - name: Build raw docs
        run: ./python/scripts/build_raw_docs.sh

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: python/.mkdocs/mkdocs.yml
